swagger: "2.0"
info:
  version: "0.0.1"
  title: Travel Groups App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /plan:
    post: 
      summary: Create a plan
      description: Create a new plan of a user
      operationId: addPlan
      parameters:
        - name: Plan
          in: body
          description: Plan to add 
          required: true
          schema: 
            $ref: "#/definitions/NewPlan"
      responses: 
        200: 
          description: plan ok response
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
  /user:
    # binds a127 app logic to a route
    post:
      summary: creates User
      description: Creates a new user of Travel Groups
      operationId: createUser
      parameters:
        - name: User
          in: body
          description: The user information
          required: true
          schema:
            $ref: "#/definitions/NewUser"
      responses:
        200:
          description: User information is OK
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
  /user/{id}/plan:
    get: 
      description: return the plan information of the user
      parameters: 
        - name: id 
          in: path
          description: ID of the user
          required: true
          type: number
      responses: 
        200: 
          description: ok
          schema: 
            $ref: "#/definitions/Plan"
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
  /user/{id}:
    get:
      summary: gets user by ID
      description: retrieves the user specified by the ID parameter
      operationId: getUserByID
      parameters:
        - name: id
          in: path
          description: ID of user to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: target user found
          schema:
            $ref: '#/definitions/User'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      
# complex objects have schema definitions
definitions:
  Transportation:
    properties:
      id: 
        type: number
      which_method:
        type: string
      arrival:
        type: string
      intr_places:
        type: string
        
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  User:
    allOf:
      - $ref: '#/definitions/NewUser'
    required:
      - id
    properties:
      id:
        type: number
      plan_id:
        type: number
      friends:
        type: array
        items:
            type: number
  NewUser:
    required:
      - name
      - password
    properties:
      name:
        type: string
      password: 
        type: string
        
  Plan: 
    allOf:
      - $ref: "#/definitions/NewPlan"
    required:
        - id
    properties:
        id: 
          type: number
        group_member:
          type: array
          items: 
            type: number
        transportations: 
          type: array
          items: 
            type: number
  NewPlan: 
    required:
      - creater
    properties:
      creater:
        type: number
      origin:
        type: string
      destination:
        type: string
      depature: 
        type: string
