swagger: "2.0"
info:
  version: "0.0.1"
  title: Travel Groups App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
    /plan:
     post: 
        summary: Create a plan
        description: Create a new plan of a user
        operationId: addPlan
        parameters:
          - name: Plan
            in: body
            description: Plan to add 
            required: true
            schema: 
              $ref: "#/definitions/NewPlan"
        responses: 
         200: 
          description: plan ok response
         default: 
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  Transportation:
    properties:
      which_method:
        type: string
      arrival:
        type: string
      intr_places:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  User:
    required:
      - name
      - id
    properties:
      name:
        type: string
      id:
        type: number
      password:
        type: string
      plan_id:
        type: number
      friends:
        type: array
        items:
            $ref: "#/definitions/User"
  Plan: 
    allOf:
      - $ref: "#/definitions/NewPlan"
      - required:
        - id
        properties:
          id: 
            type: number
          group_member:
            type: array
            items: 
              $ref: "#/definitions/User"
          transportations: 
            type: array
            items: 
              $ref: "#/definitions/Transportation"
  NewPlan: 
    required:
      - creater
    properties:
      creater:
        $ref: "#/definitions/User"
      origin: 
        type: string
      destination:
        type: string
      departure: 
        type: string